### ISSUE TITLE
LEDs randomly turning on when they should be off.

### ISSUE THREAD

**Issue by jim-at-jibba** [pimoroni/mote-phat#10]
I have written a [script](https://github.com/jim-at-jibba/mote-mqtt-desklights/blob/master/desklights.py) to change the mote lights with MQTT. But when the lights are supposed to be off some of them randomly turn back on. Often multiple different colours.

I am new to python so I imagine it is something in my script but any thoughts would be much appreciated.

Thanks

**Comment by Gadgetoid** [comment]
This is most-likely an electrical noise issue and nothing to do with your script at all.

Are you using a Mote pHAT?

Because the APA102 pixels are "smart" they tend to interpret random environmental noise as signal and attempt to display it. In order to prevent this, you need to be actively driving them periodically.
