### ISSUE TITLE
Guides written do not work with Mote pHAT

### ISSUE THREAD

**Issue by raspberrycoulis** [pimoroni/mote-phat#5]
Unless I'm missing something very obvious, the guides found [here](https://learn.pimoroni.com/tutorial/sandyj/getting-started-with-mote) do not work with the Mote pHAT. For example, the "Lighting Pixels" section, getting to `mote = Mote()` produces `IOError: Unable to find Mote device`.

Looking at the libraries between Mote and Mote pHAT, there is no `Mote` class defined in the Mote pHAT library from what I can see. This also means that the [Using Mote with Homekit and Siri](https://learn.pimoroni.com/tutorial/sandyj/using-mote-with-homekit-and-siri) does not work, as it falls down in the same place - `IOError: Unable to find Mote device`.

**Comment by raspberrycoulis** [comment]
I've been tweaking a few things based on your recommendations over Twitter, I've managed to get the API to work for the Mote Homekit with Siri guide, but only half the stick lights up:

	from colorsys import hsv_to_rgb, rgb_to_hsv
	import motephat
	from flask import Flask, jsonify, make_response

	app = Flask(__name__)

	motephat.configure_channel(1, 16, False)
	motephat.configure_channel(2, 16, False)
	motephat.configure_channel(3, 16, False)
	motephat.configure_channel(4, 16, False)

	colour = 'FFFFFF'
	status = 0

	def hex_to_rgb(value):
		value = value.lstrip('#')
		length = len(value)
		return tuple(int(value[i:i + length / 3], 16) for i in range(0, length, length / 3))

	def mote_on(c):
		r, g, b = hex_to_rgb(c)
		for channel in range(4):
			for pixel in range(16):
				motephat.set_pixel(channel + 1, pixel, r, g, b)
		motephat.show()
		return True

	def mote_off():
		motephat.clear()
		motephat.show()
		return True

	def get_status():
		global status
		for channel in range(4):
			for pixel in range(16):
				if motephat.get_pixel(channel + 1, pixel) != (0, 0, 0):
					status = 1
		return status

	@app.route('/mote/api/v1.0/<string:st>', methods=['GET'])
	def set_status(st):
		global status, colour
		if st == 'on':
			status = 1
			mote_on(colour)
		elif st == 'off':
			status = 0
			mote_off()
		elif st == 'status':
			status = get_status()
		return jsonify({'status': status, 'colour': colour})

	@app.route('/mote/api/v1.0/set', methods=['GET'])
	def get_colour():
		global colour
		return jsonify({'status': status, 'colour': colour})

	@app.route('/mote/api/v1.0/set/<string:c>', methods=['GET'])
	def set_colour(c):
		global status, colour
		colour = c
		if status != 0:
			mote_on(colour)
			status = 1
		return jsonify({'status': status, 'colour': colour})

	@app.errorhandler(404)
	def not_found(error):
		return make_response(jsonify({'error': 'Not found'}), 404)

	if __name__ == '__main__':
		mote_off()
		app.run(host='0.0.0.0', debug=True)

**Comment by Gadgetoid** [comment]
Mote and Mote pHAT differ slightly in how they're set up:

Mote pHAT is a singleton module, you `import` the module and you're good to go- this is because you can only realistically ever have *one* Mote pHAT connected to your Raspberry Pi.

Mote is a class, which you need to create an instance of. This instance can accept a serial port path, which lets you set up multiple Mote instances for multiple devices, ie:

```
import mote
moteA = mote.Mote("/dev/ttyUSB0")
moteB = mote.Mote("/dev/ttyUSB1")
```

(Mote should also work on *any* system which supports USB, whereas Mote pHAT is Pi only)

While that wont change, it looks like something has gone awry with the APIs of Mote and Mote pHAT- which should otherwise be identical- and I'll be making some changes to harmonise them so examples are easier to port.

@sandyjmacdonald could you update the Mote guide to mention something about using Mote pHAT?
